//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.OtpService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OtpService.ISmsGateway")]
    public interface ISmsGateway {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsGateway/SendOtp", ReplyAction="http://tempuri.org/ISmsGateway/SendOtpResponse")]
        string SendOtp(string otpUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsGateway/SendOtp", ReplyAction="http://tempuri.org/ISmsGateway/SendOtpResponse")]
        System.Threading.Tasks.Task<string> SendOtpAsync(string otpUrl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmsGatewayChannel : Dekhlo.Web.OtpService.ISmsGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsGatewayClient : System.ServiceModel.ClientBase<Dekhlo.Web.OtpService.ISmsGateway>, Dekhlo.Web.OtpService.ISmsGateway {
        
        public SmsGatewayClient() {
        }
        
        public SmsGatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsGatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsGatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendOtp(string otpUrl) {
            return base.Channel.SendOtp(otpUrl);
        }
        
        public System.Threading.Tasks.Task<string> SendOtpAsync(string otpUrl) {
            return base.Channel.SendOtpAsync(otpUrl);
        }
    }
}
