//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cateogry
    {
        public Cateogry()
        {
            this.PostCateogryMappings = new HashSet<PostCateogryMapping>();
            this.SubCateogries = new HashSet<SubCateogry>();
            this.SubCateogries1 = new HashSet<SubCateogry>();
            this.VisitorCateogries = new HashSet<VisitorCateogry>();
        }
    
        public long Id { get; set; }
        public string CateogryName { get; set; }
        public Nullable<bool> IsVisitorCateogry { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdateBy { get; set; }
    
        public virtual StatusCondition StatusCondition { get; set; }
        public virtual ICollection<PostCateogryMapping> PostCateogryMappings { get; set; }
        public virtual ICollection<SubCateogry> SubCateogries { get; set; }
        public virtual ICollection<SubCateogry> SubCateogries1 { get; set; }
        public virtual ICollection<VisitorCateogry> VisitorCateogries { get; set; }
    }
}
