//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostCateogryMapping
    {
        public long Id { get; set; }
        public Nullable<long> PostId { get; set; }
        public Nullable<long> CateogryId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdateBy { get; set; }
    
        public virtual Cateogry Cateogry { get; set; }
        public virtual Post Post { get; set; }
    }
}
