//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    [MetadataType(typeof(EnquiryMeta))]
    public partial class Enquiry
    {
    }

    public partial class EnquiryMeta
    {
        public long Id { get; set; }

        public string EmailTo { get; set; }

        [Display(Name = "Email From")]
        [Required]
        public string EmailFrom { get; set; }

        [Display(Name = "FromMobile Number")]
        [Required]
        public string FromMobileNumber { get; set; }

        [Display(Name = "Enquiry Subject")]
        [Required]
        public string EnquirySubject { get; set; }

        [Display(Name = "Enquiry Description ")]
        [Required]
        public string EnquiryDescription { get; set; }

        [Display(Name = "Enquiry Document ")]
        public string EnquiryDocument { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdateBy { get; set; }

        public virtual StatusCondition StatusCondition { get; set; }
    }
}
