//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        public long Id { get; set; }
        public string EmailTo { get; set; }
        public string EmailFrom { get; set; }
        public string FromMobileNumber { get; set; }
        public string EnquirySubject { get; set; }
        public string EnquiryDescription { get; set; }
        public string EnquiryDocument { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdateBy { get; set; }
    
        public virtual StatusCondition StatusCondition { get; set; }
    }
}
