//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(LogoMeta))]
    public partial class Logo
    {
    }

    public partial class LogoMeta
    {
        public int Id { get; set; }

        [Display(Name = "Image Content")]
        public byte[] ImageContent { get; set; }


        [Display(Name = "Tag Content")]
        public string TagContent { get; set; }
    }
}
