//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemoryPicture
    {
        public long Id { get; set; }
        public long MemoryId { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Memory Memory { get; set; }
    }
}
