//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MemoryPictureMeta))]
    public partial class MemoryPicture
    {
    }

    public partial class MemoryPictureMeta
    {
        public long Id { get; set; }

        [Display(Name = "Memory Id")]
        public Nullable<long> MemoryId { get; set; }

        [Display(Name = "Image Url")]
        public string ImageUrl { get; set; }

        public virtual Memory Memory { get; set; }
    }
}
