//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MemoryMeta))]
    public partial class Memory
    {
    }


    public partial class MemoryMeta
    {
        //public Memory()
        //{
        //    this.MemoryPictures = new HashSet<MemoryPicture>();
        //}

        public long Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Display(Name = "About Places Where You Have Visited")]
        public string Description { get; set; }

        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }

        [Display(Name = "Created By")]
        public Nullable<long> CreatedBy { get; set; }

        [Display(Name = "Updated On")]
        public Nullable<System.DateTime> UpdatedOn { get; set; }

        [Display(Name = "Updated By")]
        public Nullable<long> UpdatedOBy { get; set; }

        public virtual ICollection<MemoryPicture> MemoryPictures { get; set; }
    }
}
