//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [MetadataType(typeof(PageContentMeta))]
    public partial class PageContent
    {
    }

    public partial class PageContentMeta
    {
        public int Id { get; set; }

        [Display(Name = "Page Type")]
        public string PageType { get; set; }

        [AllowHtml]

        [Display(Name = "Page Text")]
        public string PageText { get; set; }

        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }

        [Display(Name = "Created By")]
        public Nullable<long> CreatedBy { get; set; }

        [Display(Name = "Updated On")]
        public Nullable<System.DateTime> UpdatedOn { get; set; }

        [Display(Name = "Update By")]
        public Nullable<long> UpdateBy { get; set; }
    }
}
