//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(PopularSearchMeta))]
    public partial class PopularSearch
    {
    }

    public partial class PopularSearchMeta
    {
        public long Id { get; set; }

        [Display(Name = "Search Parameter")]
        public string SearchParameter { get; set; }

        [Display(Name = "Searched Id")]
        public Nullable<long> SearchedId { get; set; }
    }
}
