//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [MetadataType(typeof(PostMeta))]
    public partial class Post
    {
    }

    public partial class PostMeta
    {
        //public Post()
        //{
        //    this.PostCateogryMappings = new HashSet<PostCateogryMapping>();
        //    this.PostImages = new HashSet<PostImage>();
        //}

        public long Id { get; set; }

        [Display(Name = "Post Title")]
        public string PostTitle { get; set; }

        [Display(Name = "Post Content")]
        [AllowHtml]
        [Required]
        public string PostContent { get; set; }

        public int Status { get; set; }

        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }

        [Display(Name = "Created By")]
        public Nullable<long> CreatedBy { get; set; }

        [Display(Name = "Updated On")]
        public Nullable<System.DateTime> UpdatedOn { get; set; }

        [Display(Name = "Update By")]
        public Nullable<long> UpdateBy { get; set; }

        [Display(Name = "Post Type")]
        public string PostType { get; set; }

        [Display(Name = "Status Condition ")]

        public virtual StatusCondition StatusCondition { get; set; }
        public virtual ICollection<PostCateogryMapping> PostCateogryMappings { get; set; }
        public virtual ICollection<PostImage> PostImages { get; set; }
    }
}
