//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.PostCateogryMappings = new HashSet<PostCateogryMapping>();
            this.PostImages = new HashSet<PostImage>();
        }
    
        public long Id { get; set; }
        public string PostTitle { get; set; }
        public string PostContent { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public string PostType { get; set; }
        public long UserId { get; set; }
    
        public virtual StatusCondition StatusCondition { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
        public virtual ICollection<PostCateogryMapping> PostCateogryMappings { get; set; }
        public virtual ICollection<PostImage> PostImages { get; set; }
    }
}
