//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(PostCateogryMappingMeta))]
    public partial class PostCateogryMapping
    {
    }

    public partial class PostCateogryMappingMeta
    {
        public long Id { get; set; }

        [Display(Name = "Post Id")]
        public Nullable<long> PostId { get; set; }

        [Display(Name = "Cateogry Id")]
        public Nullable<long> CateogryId { get; set; }

        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }

        [Display(Name = "Created By")]
        public Nullable<long> CreatedBy { get; set; }

        [Display(Name = "Updated On")]
        public Nullable<System.DateTime> UpdatedOn { get; set; }

        [Display(Name = "Update By")]
        public Nullable<long> UpdateBy { get; set; }



        public virtual Post Post { get; set; }


        public virtual Cateogry Cateogry { get; set; }
    }
}
