//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pvc
    {
        public Pvc()
        {
            this.PvcAdharDocuments = new HashSet<PvcAdharDocument>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public int NumberofCopies { get; set; }
        public string PinCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<bool> IsTermAccepted { get; set; }
    
        public virtual UserRegistration UserRegistration { get; set; }
        public virtual ICollection<PvcAdharDocument> PvcAdharDocuments { get; set; }
    }
}
