//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search
    {
        public Nullable<long> Id { get; set; }
        public long ContentId { get; set; }
        public string Title { get; set; }
        public string SearchContent { get; set; }
        public string SearchType { get; set; }
    }
}
