//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(SliderConfigMeta))]
    public partial class SliderConfig
    {
    }
    
    public partial class SliderConfigMeta
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
    }
}
