//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusCondition
    {
        public StatusCondition()
        {
            this.Cateogries = new HashSet<Cateogry>();
            this.UserRegistrations = new HashSet<UserRegistration>();
            this.Posts = new HashSet<Post>();
            this.Enquiries = new HashSet<Enquiry>();
        }
    
        public int Id { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<Cateogry> Cateogries { get; set; }
        public virtual ICollection<UserRegistration> UserRegistrations { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Enquiry> Enquiries { get; set; }
    }
}
