//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(StatusConditionMeta))]
    public partial class StatusCondition
    {
    }

    public partial class StatusConditionMeta
    {
        //public StatusCondition()
        //{
        //    this.Posts = new HashSet<Post>();
        //    this.UserRegistrations = new HashSet<UserRegistration>();
        //    this.Cateogries = new HashSet<Cateogry>();
        //}

        public int Id { get; set; }

        [Display(Name = "Status Name")]
        public string StatusName { get; set; }

        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<UserRegistration> UserRegistrations { get; set; }
        public virtual ICollection<Cateogry> Cateogries { get; set; }
    }
}
