//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistration
    {
        public UserRegistration()
        {
            this.VisitorCateogries = new HashSet<VisitorCateogry>();
            this.Pvcs = new HashSet<Pvc>();
            this.SearchYourNeeds = new HashSet<SearchYourNeed>();
            this.Memories = new HashSet<Memory>();
            this.Posts = new HashSet<Post>();
            this.Otps = new HashSet<Otp>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string UserName { get; set; }
        public byte[] ProfilePic { get; set; }
        public Nullable<bool> IsVisitor { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public string PinCode { get; set; }
    
        public virtual StatusCondition StatusCondition { get; set; }
        public virtual ICollection<VisitorCateogry> VisitorCateogries { get; set; }
        public virtual ICollection<Pvc> Pvcs { get; set; }
        public virtual ICollection<SearchYourNeed> SearchYourNeeds { get; set; }
        public virtual ICollection<Memory> Memories { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Otp> Otps { get; set; }
    }
}
