//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekhlo.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(VisitorCateogryMeta))]
    public partial class VisitorCateogry
    {
    }
    
    public partial class VisitorCateogryMeta
    {
        public long Id { get; set; }

        [Display(Name = "Visitor Id")]
        public long VisitorId { get; set; }

        [Display(Name = "Cateogry Id")]
        public long CateogryId { get; set; }

        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }

        [Display(Name = "Created By")]
        public Nullable<long> CreatedBy { get; set; }

        [Display(Name = "Updated On")]
        public Nullable<System.DateTime> UpdatedOn { get; set; }

        [Display(Name = "Update By")]
        public Nullable<long> UpdateBy { get; set; }

        [Display(Name = "User Registration")]
    
        public virtual UserRegistration UserRegistration { get; set; }
        public virtual Cateogry Cateogry { get; set; }
    }
}
